name: my-first-action
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        id: greet
        uses: actions/hello-world-javascript-action
        with:
          who-to-greet: Gandhiji
      - name: print
        run: echo "${{ steps.greet.outputs.time}}"
