name: myworkflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1 - shell cmds
        run: echo 'step1 is executed!'
      - name: step2 - multiline cmds
        run: |
          npm -v
          date
          uname -a
          pwd
          ps -ef
