name: my simple workflow
on: [push]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo 'hello'
      - name: save in db
        run: echo 'saving in db...'
      - name: slack & email status
        run: |
          echo 'slacking'
          echo 'mailing'
      - name: checking status
        run: echo 'all good'
