name: shellscript workflow
on: [push]
jobs:
  singleline-shell-cmds:
    runs-on: ubuntu-latest
    steps:
      - name: npm-versions
        run: npm -v
  multiline-shell-cmds:
    runs-on: ubuntu-latest
    steps:
      - name: linux-cmds
        run: |
          uname -a
          date
