name: file encode-decode workflow
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: decode file
        run: |
          echo 'start decoding file...'
          echo 'file-content: hello world!'
          echo 'completed decoding file!'
      - name: send mail
        run: |
          echo 'fetch dest list...'
          echo 'sending mail...'
          echo 'mail sent!'
